### ISSUE TITLE
YouSaly By Khalid

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/sp.pk#43]
1- coupon code not  working 
2-  quick view  close  button  not add
3-  thanks  page  proper design  **(RFR)**
4- **(RFR)**
![image](https://user-images.githubusercontent.com/33339700/40677928-87a7f8ce-6398-11e8-8ffe-31d8a2e834bb.png)
notification should  be  clear  when  click  on it  and  delete  function  not  working
5-
![image](https://user-images.githubusercontent.com/33339700/40678123-0bede4e0-6399-11e8-8b8a-4ce82983304b.png)
Grand Total  not coorect    **(RFR)**
6- On change  quantity  is  not working 
7- use  trankcate  function  for  product title  show  title in one  line 
8- on subcribe  Show  message  
9- main Search  make click able  link  
10 -  add  link at  quick  order
11-  User  Dashboard  please  show  relevent data  all  link  not show  relevant  page   **(RFR)**
12-
![image](https://user-images.githubusercontent.com/33339700/40680441-987199ec-639f-11e8-87e3-45c371ad41c4.png)
detail page small images  on click no working  it  should  be  show  in big  size  on click
![image](https://user-images.githubusercontent.com/33339700/40680552-ee568818-639f-11e8-85c9-0622571d07d0.png)
13- Delete Extra  folder  of  images only show  requird

**Comment by khalidjavaid** [comment]
1)	In all scree where we have used “True|False” be default set it “False”  from backend. Instead of Not Set **RFR**
2)	In social account use  “#” **RFR**
3)	If I don’t add photo from backend default Image  sh’d be save right now its showing missing image  
**RFR**
4)	For color code text box “Use Color” Picker in all screen (ADIL)
Also add duplicate check on “Color” and “Size “ screren
5)	In color and size check from net and add data in both tables, choose from any clothing website
6)	If I add new Product and click on Save it sh’d show me other tab instead of nothing happening(ADIL)
7)	If add “new product” it sh’d be displayed on top. Instead of bottom.
8)	On Search Filter Dropdown set default value as “All” instead of “Select” **RFR**
9)	Use Captcha on register page.
10)	On add to favirte list
11)
